<a href="https://colab.research.google.com/github/NataliaSalaberry/INTRODUCCION-A-PYTHON-PARA-LA-RESOLUCION-DE-PROBLEMAS/blob/main/IPRPAD_Cap%C3%ADtulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<figure>
<center>
<img src='https://github.com/NataliaSalaberry/INTRODUCCION-A-PYTHON-PARA-LA-RESOLUCION-DE-PROBLEMAS/blob/main/cropped-logo_FCE.png?raw=true' />
</figure>

## **Introducción a Python para la Resolución de Problemas**

###**CAPÍTULO 2**

#### **Natalia R. Salaberry**

## **Sección 2.2 Tipo de datos de uso frecuente en Python**

###**Sección 2.2.1 Numbers**



#### **Suma**

In [ ]:
2+1

3

In [ ]:
2.1+1.1

3.2

In [ ]:
# para operar con fracciones, se requiere importar una librería

from fractions import Fraction

# para definir una fracción, la función a utilizar es Fraction()
Fraction(1,2)+Fraction(1,3)

Fraction(5, 6)

In [ ]:
1 + Fraction(1,2)

Fraction(3, 2)

In [ ]:
1.1 + Fraction(1,2)

1.6

De las dos celdas anteriores ejecutadas, observar que:

- si se combina un número entero con una fracción, el resultado será una fracción

- si se combina un número decimal con una fracción, el resultado será un número decimal

In [ ]:
#se puede operar combinando los tres diferentes tipos de números

1 + 2.1 + Fraction(1,2)

3.6

#### **Resta**

In [ ]:
2-1

1

In [ ]:
2.2-1.1

1.1

In [ ]:
Fraction(1,2)-Fraction(1,3)

#observar que no se requiere importar nuevamente la librería, una vez que ya fue importada previamente, mateniendo la sesión activa
#en caso contrario, deberá importar la librería

Fraction(1, 6)

In [ ]:
1.2 - Fraction(1,2)

0.7

In [ ]:
#se puede operar combinando los tres diferentes tipos de números
4 - 2.1 - Fraction(1,2)

1.4

#### **Multiplicación**

In [ ]:
# Multiplicación
2*2

4

In [ ]:
2.5*3.5

8.75

In [ ]:
Fraction(1,2)*Fraction(1,3)

#observar que no se requiere importar nuevamente la librería, una vez que ya fue importada previamente, mateniendo la sesión activa
#en caso contrario, deberá importar la librería

Fraction(1, 6)

In [ ]:
1*2.5*Fraction(1,2)

1.25

#### **División**

In [ ]:
# Division
4/2

2.0

In [ ]:
4.2/2.1

2.0

In [ ]:
Fraction(1,2)/Fraction(1,3)

#observar que no se requiere importar nuevamente la librería, una vez que ya fue importada previamente, mateniendo la sesión activa
#en caso contrario, deberá importar la librería

Fraction(3, 2)

In [ ]:
4/2.1/Fraction(1,2)

3.8095238095238093

In [ ]:
#división: obtener resultado
5//2

2

In [ ]:
#división: obtener resto
5 % 2

1

#### **Potencia**

In [ ]:
#Potencia
2**2

4

In [ ]:
2.2**2.2

5.666695778750081

In [ ]:
Fraction(1,2)**Fraction(1,3)

#observar que no se requiere importar nuevamente la librería, una vez que ya fue importada previamente, mateniendo la sesión activa
#en caso contrario, deberá importar la librería

0.7937005259840998

In [ ]:
(2**2.2)**Fraction(1,2)

2.1435469250725863

#### **Raíz**

In [ ]:
#Raíz cuadrada
4**0.5

2.0

In [ ]:
#Raíz cúbica
8**(1/3)

2.0

In [ ]:
4.2**0.5

2.04939015319192

In [ ]:
Fraction(1,4)**0.5

0.5

#### **Asignación**

Demos un paso más y asignemos el resultado de la operación a un objeto definiendole el tipo con la función asociada a los números

In [ ]:
resultado0=2*2
resultado0

4

In [ ]:
resultado0=2*2
print(resultado0)

resultado00=2*3
print(resultado00)


4
6


In [ ]:
#También es posible asignar el resultado de una operación, definiendo el tipo de número al resultado que se obtiene
resultado1=int(2*2)
resultado1

4

In [ ]:
#se consulta el tipo del objeto creado
type(resultado1)

int

In [ ]:
# si en cambio se utiliza int(), solo devolverá la parte entera del resultado
resultado2=int(3/2)
resultado2

1

In [ ]:
# si en cambio se utiliza float() devolverá el resultado completo
resultado2=float(3/2)
resultado2

1.5

Entonces cuando definimos un variable con un tipo entero, solo nos mostrará la parte entera del resultado numérico para la división del ejemplo. Hay que tener cuidado con el tipo que se define.

In [ ]:
# el tipo adecuado a definir de la variable que involucra una operación de división es
resultado3=float(3/2)
resultado3

1.5

In [ ]:
type(resultado3)

float

#### **Redondear**

In [ ]:
#si quisieramos redondear un número

round(1.2345,2) #donde el 2 (después de la coma) es la cantidad de decimales a obtener como resultado del redondeo

1.23

In [ ]:
round(1.235,2)

1.24

In [ ]:
#siempre que el contenido del objeto sea un número, es posibel aplicar la función round()
round(resultado3,1)

1.5

####**Ejemplos sección 2.2.1**

**Ejemplo 2.1**

Resolver la siguiente operación:

$({3.1+ \sqrt 4 \over {1\over 2}*5})^2$

In [ ]:
((3.1+(4**0.5)) / (Fraction(1,2)*5))**2

4.1616

**Ejemplo 2.2**

Suponga que se requiere crear un programa donde un usuario pueda ingresar el número de horas trabajadas y lo que cobra por hora. Como resultado se pretende obtener el pago que deberá recibir.

In [ ]:
horas = float(input("Introduce tus horas de trabajo: "))
costo = float(input("Introduce lo que cobras por hora: "))
pago = horas * costo
print("El pago a recibir es $" + str(horas * costo))

Introduce tus horas de trabajo: 10
Introduce lo que cobras por hora: 200
El pago a recibir es $2000.0


###**Sección 2.2.2 Strings**


#### **Creación de un String**

In [ ]:
#se crea un string
"Ciencias Económicas"

'Ciencias Económicas'

In [ ]:
# si se asigna a un objeto, luego se invoca para observar el contenido
texto="Ciencias Económicas"
texto

'Ciencias Económicas'

#### **Acceso a elementos**

Al ser una cadena de texto, contiene varios elementos (cada letra será un elemento, pero el espacio en blanco también). Entonces si se quiere obtener un elemento en particular de la cadena deberá utilizarse el indice.
En Python, la posición de los elemento comienza en cero.

In [ ]:
# la primer letra
texto[0]

'C'

In [ ]:
# algún elemento de la cadena
texto[2]

'e'

In [ ]:
# el útlimo elemento de la cadena
texto[-1]

's'

In [ ]:
# si se quiere obtener todo lo anterior a una posición determinada
texto[:15]

'Ciencias Económ'

In [ ]:
# o todo lo posterior
texto[15:]

'icas'

In [ ]:
# si se quiere obtener desde una posición a otra
texto[0:9]

'Ciencias '

####**Funciones más frecuentemente**

In [ ]:
# cantidad de elementos de la cadena (incluye los espacios en blanco)
len(texto)

19

In [ ]:
#convertir a mayúsculas
texto.upper()

'CIENCIAS ECONÓMICAS'

In [ ]:
# convertir a minúscula
texto.lower()

'ciencias económicas'

In [ ]:
# separar la cadena por cada espacio en blanco
texto.split()

['Ciencias', 'Económicas']

In [ ]:
# separar la cadena por alguna letra
texto.split("a")

['Cienci', 's Económic', 's']

Algo común de realizar es la concatenación

In [ ]:
texto + ' 2025'


'Ciencias Económicas 2025'

In [ ]:
#asignarloa  un nuevo objeto
texto1=texto + ' 2025'
texto1

'Ciencias Económicas 2025'

In [ ]:
# si se requiere generar una repetición:
texto1*4

'Ciencias Económicas 2026Ciencias Económicas 2026Ciencias Económicas 2026Ciencias Económicas 2026'

In [ ]:
#reemplazar el 5 por el 6
texto1=texto1.replace('5', '6')
texto1

'Ciencias Económicas 2026'

#### **Ejemplos Sección 2.2.2**

**Ejemplo 2.2.2.1**

A partir de la siguiente oración “La inflación de mayo 2026 es 2,1%” realice lo siguiente:

-	Cree un objeto string con el nombre texto que contenga la oración

-	Separe el texto

-	Obtenga el elemento “2,1%” y asigneló a un objeto denominado valor

-	Separe el objeto por %

- Reemplace la coma por un punto

-	Obtengan el elemento 2.1

-	Conviértalo a número

-	Imprima el resultado


In [ ]:
texto="La inflación de mayo 2026 es 2.1%"
texto=texto.split()
valor=texto[-1]
valor=valor.split("%")
valor=valor[0]
valor=valor.replace(",",".")
valor=float(valor)
print(valor)

2.1


**Ejemplo 2.2.2.2**

Escriba un programa que solicite al usuario que ingrese su primer nombre y apellido en minúscula. Conviertalo a mayúscula. A partir de ello, obtenga las iniciales. Finalmente, se pretende que el programa devuelva las iniciales del usuario.

In [ ]:
nombre=input('Ingresa su primer nombre y su apellido en minúscula: ')
nombre=nombre.upper()
nombre=nombre.split()
print('Las iniciales del usuario son: '+ nombre[0][0]+nombre[1][0])

Ingresa su primer nombre y su apellido en minúscula: juan lópez
Las iniciales del usuario son: JL


###**Sección 2.2.3 Booleans**

In [ ]:
#¿uno es mayor que dos?

1>2

False

In [ ]:
#¿dos es mayor que uno?

2>1

True

In [ ]:
#¿dos es mayor o igual que uno?

2>=1

True

In [ ]:
# ¿a es igual a b?

"a"=="b"

False

In [ ]:
# ¿a es distinto que b?

"a"!="b"

True

In [ ]:
#se definen dos objetos string

texto1="casa"
texto2="CASA"

In [ ]:
#si se pregunta si texto1 es igual a texto 2, se obtiene
texto1==texto2

False

Recuerde que Python es Case Sensitive, razón por la cual la palabra escrita con mayúscula o minúscula no serpa lo mismo para Python, a diferencia de la comprensión humana al leerla.

Aplicando alguna de las funciones vistas para strings es posible llegar a resultados diferentes

In [ ]:
texto1.upper()==texto2

True

In [ ]:
texto1==texto2.lower()


True

Si la pregunta hubiese sido sobre cantidad de elementos contenidos en cada string

In [ ]:
texto3=len(texto1)
texto4=len(texto2)

In [ ]:
texto3==texto4

#entonces ahora si es un resultado verdadero directamente.

True

####**Ejemplos Sección 2.2.3**

**Ejemplo 2.2.3.1**

Indique verdadero o falso verificando con Python:

1.	"%"=="%"

2. $12.54 > 12.53$

3.  $ {1 \over 2} >=  {4 \over 2}$


In [ ]:
"%"=="%"

True

In [ ]:
12.54 > 12.53

True

In [ ]:
from fractions import Fraction

Fraction(1,2) >= Fraction(4,2)

False


**Ejemplo 2.2.3.1**

Escriba un programa donde el usuario ingrese una palabra dos veces: en minúscula y en mayúscula. Luego conviértalas a mayúscula. Se desea obtener como resultado si ambas palabras son iguales o no.

In [ ]:
palabra1=input('Ingrese una palabra en minúscula: ')
palabra2=input('Ingrese la misma palabra en mayúscula: ')
palabra1=palabra1.upper()
palabra2=palabra2.upper()
print('Las palabras ingresadas, ¿son iguales? '+ str(palabra1==palabra1))

Ingrese una palabra en minúscula: casa
Ingrese la misma palabra en mayúscula: CASA
Las palabras ingresadas, ¿son iguales? True


###**Sección 2.2.4 Date**

In [ ]:
#importación de librería
from datetime import datetime

In [ ]:
#obtener la fecha actual
datetime.now()

datetime.datetime(2026, 6, 26, 20, 8, 7, 693409)

In [ ]:
#se define una fecha como string (podría ser un tipo object y sería lo mismo)
FECHA='2026-6-26 20:08:07' #siempre observar el orden de año, mes, día para el idioma inglés.
FECHA

'2026-6-26 20:08:07'

In [ ]:
#convertir a DateTime: internamente es un número (como sucede en excel) y por tanto se podrá hacer operaciones aritméticas
DATETIME = datetime.strptime(FECHA, '%Y-%m-%d %H:%M:%S') # FECHA podría ser un tipo object y sería lo mismo

print(DATETIME) #fecha completa
print(DATETIME.date()) #Año, mes, dia
print(DATETIME.year) #Año
print(DATETIME.month) #mes
print(DATETIME.day) #dia
print(DATETIME.weekday()) #número de día de la semana
print(DATETIME.hour) #hora
print(DATETIME.minute) #minuto
print(DATETIME.second) #segundo

2026-06-26 20:08:07
2026-06-26
2026
6
26
4
20
8
7


In [ ]:
#Si es DateTime se puede convertir a string y obtener otras variantes
fecha=DATETIME.strftime('%Y-%m-%d %H:%M:%S')
print(fecha)

print(DATETIME.strftime('%y')) #número año acotado
print(DATETIME.strftime('%Y')) #número año completo

print(DATETIME.strftime('%m')) #número mes
print(DATETIME.strftime('%b')) #nombre mes acotado
print(DATETIME.strftime('%B')) #nombre mes completo

print(DATETIME.strftime('%a')) #nombre del día acotado
print(DATETIME.strftime('%A')) #nombre del día completo
print(DATETIME.strftime('%j')) #número del día en el año

print(DATETIME.strftime('%W')) #número de semana del año

print(DATETIME.strftime('%H')) #hora
print(DATETIME.strftime('%M')) #minuto
print(DATETIME.strftime('%S')) #segundo

2026-06-26 20:08:07
26
2026
06
Jun
June
Fri
Friday
177
25
20
08
07


####**Ejemplo Sección 2.2.4**

**Ejemplo 2.2.4.1**

In [ ]:
DATETIME_1 = datetime.strptime('2026-1-1', '%Y-%m-%d')
DATETIME_2 = datetime.strptime('2025-1-1', '%Y-%m-%d')
DATETIME_1 - DATETIME_2

datetime.timedelta(days=365)

**Ejemplo 2.2.4.2**

Escriba un programa donde el usuario ingrese su fecha de nacimiento en formato AÑO/MES/DIA y devuelva "La fecha de nacimiento es DIA NÚMERO de NOMBRE DEL MES EN ESPAÑOL de AÑO NÚMERO"

In [ ]:
FECHA=input('Ingresa la fecha en formato AÑO/MES/DIA: ')
FECHA=datetime.strptime(FECHA, '%Y/%m/%d')
DIA=FECHA.day
MESES={'January':'enero', 'February':'febrero','March':'marzo','April':'abril','May':'mayo','June':'junio','July':'julio','August':'agosto','September':'septiembre','October':'octubre','November':'noviembre','December':'diciembre'}
MES=MESES[FECHA.strftime('%B')]
AÑO=FECHA.strftime('%Y')
print('La fecha de nacimiento es '+ str(DIA) + ' de ' + MES + ' de '+ str(AÑO))

Ingresa la fecha en formato AÑO/MES/DIA: 1950/4/25
La fecha de nacimiento es 25 de abril de 1950


#### **Obtener un calendario completo**

In [ ]:
import calendar

In [ ]:
#ver el calandario completo
print(calendar.calendar(2025))

                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 

In [ ]:
#ver un mes del calendario
print(calendar.month(2025, 11))

   November 2025
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



Transformarlo a español

In [ ]:
calendario=calendar.calendar(2025).split("\n")
calendario

['                                  2025',
 '',
 '      January                   February                   March',
 'Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su',
 '       1  2  3  4  5                      1  2                      1  2',
 ' 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9',
 '13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16',
 '20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23',
 '27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30',
 '                                                    31',
 '',
 '       April                      May                       June',
 'Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su',
 '    1  2  3  4  5  6                1  2  3  4                         1',
 ' 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8',
 '14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 

In [ ]:
calendario[:4] = ["                                  2025", "",'      Enero                   Febrero                   Marzo',"Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do"]

calendario[11:13] = ['       Abril                      Mayo                       Junio',"Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do"]

calendario[20:22] = ['        Julio                     Agosto                  Septiembre',"Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do"]

calendario[28:30] = ['      Octubre                   Noviembre                  Diciembre',"Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do"]

print("\n".join(calendario))

                                  2025

      Enero                   Febrero                   Marzo
Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       Abril                      Mayo                       Junio
Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do      Lu Ma Mi Ju Vi Sa Do
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 2

In [ ]:
#Si se quiere un solo mes
noviembre = calendar.month(2025, 11).split("\n")
noviembre[:2] = ["Noviembre 2025", "Lu Ma Mi Ju Vi Sa Do"]
print("\n".join(noviembre))

Noviembre 2025
Lu Ma Mi Ju Vi Sa Do
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30



###**Sección 2.2.5 None, NaN y Zero**

In [ ]:
#valor vacío
valor_1=None
valor_1

In [ ]:
#valor NaN
valor_2=float('nan')
valor_2

nan

In [ ]:
resultado=2/float('nan')
resultado

nan

In [ ]:
#Valor cero
valor_3=0
valor_3

0

In [ ]:
resultado_3=10-10
resultado_3

0

## **Sección 2.3 Tipo de objetos más frecuentes en Python**

###**Sección 2.3.1 List**

#### **Creación de una Lista**

In [ ]:
# se crea un lista y se asigna a un objeto
lista=['uno', 'dos', 3, 4]

In [ ]:
lista

['uno', 'dos', 3, 4]

#### **Acceso a los elementos**

In [ ]:
# acceder al primer elemento
lista[0]

'uno'

In [ ]:
# acceder al tercer elemento
lista[2]

3

In [ ]:
#acceder a la primer letra del primer elemento
lista[0][0]

'u'

In [ ]:
#acceder a más de un elemento
lista[1:3]

['dos', 3]

#### **Modificación de elementos**

In [ ]:
#reemplazar un elemento de la lista
lista[0]=1

In [ ]:
lista

[1, 'dos', 3, 4]

In [ ]:
#reemplazar varios elementos de la lista
lista[0:2]=[1,2]

In [ ]:
lista

[1, 2, 3, 4]

In [ ]:
lista[:2]=[1,2]
lista

[1, 2, 3, 4]

####**Listas anidadas**

In [ ]:
#se crean tres listas
lista_1=[1,2,3]
lista_2=[4,5,6]
lista_3=[7,8,9]

In [ ]:
#se crea una lista con las tres listas anteriores
lista_all=[lista_1, lista_2, lista_3]
lista_all

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
# acceder al primer elemento
lista_all[0]

[1, 2, 3]

In [ ]:
#acceder al tercer elemento de la primera lista
lista_all[0][2]

3

In [ ]:
#acceder al primer elemento de la tercera lista
lista_all[2][0]

7

In [ ]:
#acceder a todos los elementos desde la posición uno
lista_all[1:]

[[4, 5, 6], [7, 8, 9]]

In [ ]:
#acceder únicamente al tercer elemento de la lista utilizando un rango
lista_all[1:][1]

[7, 8, 9]

In [ ]:
#acceder al primer elemento de la tercera lista utilizando un rango
lista_all[0:][2][0]

7

####**Funciones más frecuentemente**

#####**Las que NO modifican la lista**

In [ ]:
#cantidad de elementos que contiene la lista
len(lista_all)

3

In [ ]:
# Devuelve el elemento de menor valor de la lista siempre que los datos sean comparables.
min(lista_all)

[1, 2, 3]

In [ ]:
# Devuelve el elemento de mayor valor de la lista siempre que los datos sean comparables.
max(lista_all)

[7, 8, 9]

In [ ]:
#Devuelve la suma de los elementos de la lista, siempre que los datos se puedan sumar.
sum(lista)

10

In [ ]:
#Devuelve la suma de los elementos contenidos en el primer elemento de la lista, siempre que los datos se puedan sumar.
sum(lista_all[0])

6

In [ ]:
#Buscar un elemento dentro de la lista
#Devuelve True si el elemento lista indicado pertenece a la lista y False en caso contrario.
[1,2,3] in lista_all

True

In [ ]:
# Obtener la posición que ocupa en la lista un determinado elemento.
lista_all.index([1,2,3])

0

In [ ]:
# Contar las veces que un valor está contenido en la lista.
lista_all.count([1,2,3])

1

In [ ]:
# Verificar si todos los elementos de la lista son válidos.
all(lista_all)

True

In [ ]:
# Verificar si alguno de los elementos de la lista son válidos.
any(lista_all)

True

In [ ]:
#concatenar elementos
lista_all + ['item', 'item2']

[[1, 2, 3], [4, 5, 6], [7, 8, 9], 'item', 'item2']

#####**Las que SI modifican la lista**

In [ ]:
# Añadir un elemento al final de la lista.
lista.append(5)
lista

[1, 2, 3, 4, 5]

In [ ]:
# Añade los datos de una lista a otra lista.
lista_1.extend(lista_2)
lista_1

[1, 2, 3, 4, 5, 6]

In [ ]:
# Inserta None (vacío o puede ser cualquier valor) en la posición indicada de la lista
# y desplaza los elementos una posición a partir de la posición indicada.
lista_1.insert(4, None)
lista_1

[1, 2, 3, 4, None, 5, 6]

In [ ]:
# Eliminar el elemento con valor None en la lista l y desplaza los que están por detrás de él una posición hacia delante.
lista_1.remove(None)
lista_1

[1, 2, 3, 4, 5, 6]

In [ ]:
# Eliminar un elemento de la lista, desplazando los elementos por detrás de él una posición hacia delante.
lista_1.pop(4)
lista_1

[1, 2, 3, 4, 6]

In [ ]:
#invertir el orden de los elementos de una lista.
lista_2.reverse()
lista_2

[6, 5, 4]

In [ ]:
lista_2.sort() #Ordena los elementos de la lista l de acuerdo al orden predefinido, siempre que los elementos sean comparables.
lista_2

[4, 5, 6]

####**Ejemplos Sección 2.3.1**

**Ejemplo 2.3.1.1**

A partir de que un usuario ingrese los valores 1,2,3, cree una lista con ellos. Utilizando la función append() agregue el valor 4 y 4+1 a la lista. Finalmente, que se obtenga "La suma de los elementos de la lista es: suma", donde suma debe mostrar el resultado de sumar los elementos.

In [ ]:
lista=[int(input('Ingrese el valor 1: ')),int(input('Ingrese el valor 2: ')),int(input('Ingrese el valor 3: '))]
lista.append(4)
lista.append(4+1)
suma=sum(lista)
print('La suma de los elementos de la lista es: '+str(suma))

Ingrese el valor 1: 1
Ingrese el valor 2: 2
Ingrese el valor 3: 3
La suma de los elementos de la lista es: 15


**Ejemplo 2.3.1.2**

Cree una lista con los precios 100,20,30. Cree otra lista con los valores computadora, teclado, software, cuyos precios correspondientes son los de la primera lista (en ese orden). Solicite al usuario el producto sobre el cual le interesa obtener el precio. Utilícelo para obtener el índice correspondiente y que se muestre por pantalla el siguiente resultado "El precio del producto X es $P "

In [ ]:
precios=[100,20,30]
productos=['computadora', 'teclado', 'software']
pos=productos.index(input('Indique el producto en minúscula: '))
prod_elegido=productos[pos]
precio=precios[pos]
print('El precio del producto ' + str(prod_elegido) + ' es $ '+str(precio))

Indique el producto en minúscula: computadora
El precio del producto computadora es $ 100


###**Sección 2.3.2 Tuple**

#### **Creación de una tupla**

In [ ]:
# se crea una tupla y se asigna a un objeto
tupla=(1,2,'tres')

In [ ]:
tupla

(1, 2, 'tres')

Otra forma de definir una Tupla es:

In [ ]:
tupla_1=1,2,3
tupla_1

(1, 2, 3)

#### **Acceso a los elementos**

In [ ]:
# acceder al primer elemento
tupla[0]

1

In [ ]:
# acceder al tercer elemento
tupla[2]

'tres'

In [ ]:
#acceder a la primer letra del tercer elemento
tupla[2][0]

't'

In [ ]:
#acceder a más de un elemento
tupla[1:3]

(2, 'tres')

####**Inmutabilidad**

In [ ]:
tupla[0]='a'

TypeError: 'tuple' object does not support item assignment

In [ ]:
tupla.append('cuatro',)

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
#en cambio es posible al concatenación
tupla_2=tupla + ('cuatro',)
tupla_2

(1, 2, 'tres', 'cuatro')

####**Tuplas anidadas**

In [ ]:
tupla_A=(1,2,3)
tupla_B=(4,5,6)
tupla_C=(7,8,9)

tupla_all=(tupla_A, tupla_B, tupla_C)
tupla_all

((1, 2, 3), (4, 5, 6), (7, 8, 9))

In [ ]:
# acceder al primer elemento
tupla_all[0]

(1, 2, 3)

In [ ]:
#acceder al tercer elemento de la primera tupla
tupla_all[0][2]

3

In [ ]:
#acceder al primer elemento de la tercera tupla
tupla_all[2][0]

7

In [ ]:
#acceder a todos los elementos desde la posición uno
tupla_all[1:]

((4, 5, 6), (7, 8, 9))

In [ ]:
#acceder únicamente al tercer elemento de la tupla utilizando un rango
tupla_all[1:][1]

(7, 8, 9)

In [ ]:
#acceder al primer elemento de la tercera tupla utilizando un rango
tupla_all[0:][2][0]

7

####**Funciones más frecuentemente**

#####**Solo aquellas que no modifican la tupla**

In [ ]:
#cantidad de elementos que contiene la tupla
len(tupla_all)

3

In [ ]:
# Devuelve el elemento de menor valor de la tupla siempre que los datos sean comparables.
min(tupla_all)

(1, 2, 3)

In [ ]:
#Devuelve la suma de los elementos contenidos en el primer elemento de la tupla, siempre que los datos se puedan sumar.
sum(tupla_all[0])

6

In [ ]:
#Buscar un elemento dentro de la lista
#Devuelve True si el elemento tupla indicado pertenece a la tupla y False en caso contrario.
(1,2,3) in tupla_all

True

In [ ]:
# Obtener la posición que ocupa en la tupla un determinado elemento.
tupla_all.index((1,2,3))

0

In [ ]:
# Contar las veces que un valor está contenido en la lista.
tupla_all.count((1,2,3))

1

In [ ]:
# Verificar si todos los elementos de la lista son válidos.
all(tupla_all)

True

In [ ]:
# Verificar si alguno de los elementos de la lista son válidos.
any(tupla_all)

True

####**Conversión de tuplas**

In [ ]:
LISTA=list(tupla)
LISTA

[1, 2, 'tres']

In [ ]:
TUPLA=tuple(LISTA)
TUPLA

(1, 2, 'tres')

####**Ejemplos Sección 2.3.2**

**Ejemplo 2.3.2.1**

Dada la siguiente tupla que contiene las provincias argentinas (Ciudad Autónoma de Buenos Aires, Provincia de Buenos Aires, Catamarca, La Pampa, Río Negro, Santa Cruz, Tucumán, Chaco, Formosa, Misiones, San Juan, Tierra del Fuego, Corrientes, La Rioja, Neuquén, Santiago del Estero, Córdoba, Mendoza, Santa Fe, Chubut, Jujuy, San Luis, Entre Ríos, Salta), obtener una nueva tupla pero ordenada alfabéticamente.

In [ ]:
tupla_original=('Ciudad Autónoma de Buenos Aires', 'Provincia de Buenos Aires', 'Catamarca', 'La Pampa',
                'Río Negro', 'Santa Cruz', 'Tucumán', 'Chaco', 'Formosa', 'Misiones', 'San Juan', 'Tierra del Fuego',
                'Corrientes', 'La Rioja', 'Neuquén', 'Santiago del Estero', 'Córdoba', 'Mendoza', 'Santa Fe', 'Chubut',
                'Jujuy', 'San Luis', 'Entre Ríos', 'Salta')
lista=list(tupla_original)
lista.sort()
tupla_ordenada=tuple(lista)
tupla_ordenada

('Catamarca',
 'Chaco',
 'Chubut',
 'Ciudad Autónoma de Buenos Aires',
 'Corrientes',
 'Córdoba',
 'Entre Ríos',
 'Formosa',
 'Jujuy',
 'La Pampa',
 'La Rioja',
 'Mendoza',
 'Misiones',
 'Neuquén',
 'Provincia de Buenos Aires',
 'Río Negro',
 'Salta',
 'San Juan',
 'San Luis',
 'Santa Cruz',
 'Santa Fe',
 'Santiago del Estero',
 'Tierra del Fuego',
 'Tucumán')

**Ejemplo 2.3.1.2**

Cree un programa donde, a partir de un inventario existente ('A1','A2','B3','B4','C5','C6','D7','D8','D9','D10'), el usuario ingrese un código de producto y devuelva True si el producto existe en inventario o False en caso contrario

In [ ]:
prod_usuario=input('Ingrese el código de producto: ')
prod_inventario=('A1','A2','B3','B4','C5','C6','D7','D8','D9','D10')
resultado=prod_usuario in prod_inventario
print('El producto '+ str(prod_usuario)+ ' existe en inventario ' + str(resultado))

Ingrese el código de producto: A1
El producto A1 existe en inventario True


In [ ]:
prod_usuario=input('Ingrese el código de producto: ')
prod_inventario=('A1','A2','B3','B4','C5','C6','D7','D8','D9','D10')
resultado=prod_usuario in prod_inventario
print('El producto '+ str(prod_usuario)+ ' existe en inventario ' + str(resultado))

Ingrese el código de producto: C10
El producto C10 existe en inventario False


###**Sección 2.3.3 Dictionary**

####**Creación de un diccionario**

In [ ]:
#creación de un diccionario
diccionario = {'nombre':'Rosa','apellido':'Perez', 'año_nacimiento': 1983}

In [ ]:
#se observa
diccionario

{'nombre': 'Rosa', 'apellido': 'Perez', 'año_nacimiento': 1983}

También es posible crear diccionarios a partir de listas o tuplas

In [ ]:
lista1=['A','B']
lista2=[1,2]
diccionario1=dict(zip(lista1,lista2))
diccionario1

{'A': 1, 'B': 2}

In [ ]:
lista1=('A','B')
lista2=(1,2)
diccionario2=dict(zip(lista1,lista2))
diccionario2

{'A': 1, 'B': 2}

####**Acceso a los elementos**

In [ ]:
#acceder al primer elemento
diccionario['nombre']

'Rosa'

In [ ]:
#acceder a la primera letra del nombre
diccionario['nombre'][0]

'R'

#### **Modificación de elementos**

In [ ]:
diccionario['nombre']='Juan'
diccionario

{'nombre': 'Juan', 'apellido': 'Perez', 'año_nacimiento': 1983}

In [ ]:
# agregar un elemento al diccionario
diccionario['nacionalidad']='Argentina'

In [ ]:
diccionario

{'nombre': 'Juan',
 'apellido': 'Perez',
 'año_nacimiento': 1983,
 'nacionalidad': 'Argentina'}

####**Funciones más frecuentemente**

#####**Las que NO modifican un diccionario**

In [ ]:
#cantidad de elementos que contiene el diccionario
len(diccionario)

3

In [ ]:
#obtener el mínimo elemento: si son string, devuelve según orden alfabético
min(diccionario)

'apellido'

In [ ]:
#obtener el máximo elemento: si son string, devuelve según orden alfabético
max(diccionario)

'nombre'

In [ ]:
#sumar los elementos del todo el diccionario
diccionario_2={1:1,2:2,3:3}
sum(diccionario_2)

6

In [ ]:
min(diccionario_2)

1

In [ ]:
max(diccionario_2)

3

In [ ]:
#sumar elementos de otro elemento
diccionario_3={'A':1,'B':2,'C':[1,2,3]}
sum(diccionario_3['C'])

6

In [ ]:
# Buscar una clave en el diccionario
#Devuelve True si la clave clave pertenece al diccionario y False en caso contrario.
'nombre' in diccionario

True

In [ ]:
#obtener las claves del diccionario
diccionario.keys()

dict_keys(['nombre', 'apellido', 'año_nacimiento'])

In [ ]:
#obtener los valores del diccionario
diccionario.values()

dict_values(['Juan', 'Perez', 1983])

In [ ]:
#obtener todos los elementos del diccionario
diccionario.items()

dict_items([('nombre', 'Juan'), ('apellido', 'Perez'), ('año_nacimiento', 1983)])

In [ ]:
#obtener un elemento a partir de la clave
diccionario.get('nombre')

'Juan'

In [ ]:
#buscar un valor en el diccionario
'Juan' in diccionario.values()

True

In [ ]:
#vaciar un diccionario
diccionario_2.clear()
diccionario_2

{}

#####**Las que SI modifican un diccionario**

In [ ]:
#añadir los elementos de un diccionario en otro diccionario
d1={'A':1,'B':2}
d2={'C':3,'D':4}

d1.update(d2)
d1

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [ ]:
#eliminar elementos por clave
d1.pop('D')
d1

{'A': 1, 'B': 2, 'C': 3}

In [ ]:
#eliminar la última tupla clave valor
d1.popitem()
d1

{'A': 1, 'B': 2}

In [ ]:
#otra forma de eliminar items
del d1['B']
d1

{'A': 1}

####**Ejemplos Sección 2.3.3**

**Ejemplo 2.3.3.1**

Escribir un programa que guarde en un objeto el siguiente diccionario  {'Euro':'€', 'Peso':'$', 'Yen':'¥'}. Luego que el usuario ingrese el nombre de una divisa y devuelva su símbolo. En caso de que no esté en el diccionario, que muestre un mensaje de aviso.

In [ ]:
monedas = {'Euro':'€', 'Peso':'$', 'Yen':'¥'}
moneda = input("Introduce el nombre de una divisa: ")
print('El símbolo correspondiente a '+ moneda + ' es: ' + monedas.get(moneda.title(), "La moneda elegida no está."))

Introduce el nombre de una divisa: peso
El símbolo correspondiente a peso es: $


In [ ]:
moneda = input("Introduce una divisa: ")
print('El símbolo correspondiente a '+ moneda + ' es: ' + monedas.get(moneda.title(), "La moneda elegida no está."))

Introduce una divisa: dólar
El símbolo correspondiente a dólar es: La moneda elegida no está.


**Ejemplo 2.3.3.2**

Cree un programa donde el usuario introduzca 3 productos y el precio de cada uno y usted conforme un diccionario. Agregue el subtotal gastado. Luego al subtotal aplique un descuento del 15%. Al final que el programa devuelva cada item con su precio, el subtotal, el monto del descuento y el total a pagar.

In [ ]:
compra={}
item1=input('Nombre del producto1: ')
precio1=input('Precio del producto1: ')
item2=input('Nombre del producto2: ')
precio2=input('Precio del producto2: ')
item3=input('Nombre del producto3: ')
precio3=input('Precio del producto3: ')
compra[item1]=float(precio1)
compra[item2]=float(precio3)
compra[item3]=float(precio3)
compra['Subtotal']=compra.get(item1)+compra.get(item2)+compra.get(item3)
compra['Descuento']=compra['Subtotal']*0.15
compra['Total']=compra['Subtotal']-compra['Descuento']
print('El cliente compró:')
print(list(compra.keys())[0], compra.get(item1))
print(list(compra.keys())[1], compra.get(item2))
print(list(compra.keys())[2], compra.get(item3))
print(list(compra.keys())[3], compra.get('Subtotal'))
print('Se aplicó un descuento del 15%: ' + str(compra.get('Descuento')))
print('En total pagó:'+ str(compra.get('Total')))

Nombre del producto1: computadora
Precio del producto1: 1500000
Nombre del producto2: teclado
Precio del producto2: 70000
Nombre del producto3: mouse
Precio del producto3: 30000
El cliente compró:
computadora 1500000.0
teclado 30000.0
mouse 30000.0
Subtotal 1560000.0
Se aplicó un descuento del 15%: 234000.0
En total pagó:1326000.0


###**Sección 2.3.4 Array**

####**Creación de un Array**

In [ ]:
import numpy as np

In [ ]:
#vector con un elemento numérico
np.array([1])

array([1])

In [ ]:
#array con 4 elementos numéricos
vector=np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [ ]:
#vector fila con 4 elementos
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [ ]:
#vector columna con 4 elementos numéricos
np.array([[1],[2],[3],[4]])

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
#crear un vector con valores entre 1 y 10
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#crear un vector con valores entre 1 y 10, saltando de a dos
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
#crear un array a partir de una lista
lista=[1,2]
vector_l=np.array(lista)
vector_l


array([1, 2])

In [ ]:
#crear un array a partir de una tupla
tupla=(1,2)
vector_t=np.array(tupla)
vector_t

array([1, 2])

####**Acceso a los elementos**

In [ ]:
#acceder al primer elemento
vector[0]

np.int64(1)

In [ ]:
#acceder al segundo elemento
vector[1]

np.int64(2)

In [ ]:
#acceder a un rango de elementos
vector[0:2] #el segundo valor es un hasta (no lo incluye)

array([1, 2])

#### **Modificación de elementos**

In [ ]:
#reemplazar el primer elemento
vector[0]=0
vector

array([0, 2, 3, 4])

In [ ]:
#reemplazar de a varios elementos
vector[0:2]=[1,2]
vector

array([1, 2, 3, 4])

In [ ]:
#agregar un elemento
vector=np.append(vector,5)
vector

array([1, 2, 3, 4, 5])

####**Funciones más frecuentes**

#####**Las que NO modifican un array**

In [ ]:
#cantidad de elementos
len(vector)

5

In [ ]:
#cantidad de elementos del array
vector.size

5

In [ ]:
#dimensión de un array: todo vector tiene dimensión 1
vector.ndim

1

In [ ]:
#dimensiones de un vector fila
vector_1=np.array([[1,2,3,4]])
vector_1.shape

(1, 4)

In [ ]:
#dimensiones de un vector columna
vector_2=np.array([[1],[2],[3],[4]])
vector_2.shape

(4, 1)

In [ ]:
#tipo de datos de los elementos del array
vector.dtype

dtype('int64')

In [ ]:
#preguntar si un valor existe en el array
5 in vector

True

In [ ]:
#maximo valor
np.max(vector)

np.int64(5)

In [ ]:
#mínimo valor
np.min(vector)

np.int64(1)

In [ ]:
#sumar los valores
np.sum(vector)

np.int64(15)

#####**Las que SI modifican un array**

In [ ]:
#agregar un elemento, si se usa asignación
vector_3=np.append(vector, 6)
vector_3

array([1, 2, 3, 4, 5, 6])

In [ ]:
#agregar más de un elemento, si se usa asignación
vector_3=np.append(vector, [6,7])
vector_3

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#ordenar elementos
vector0=np.array([4,3,2,1])
vector0.sort()
vector0

array([1, 2, 3, 4])

In [ ]:
#insertar nuevos elementos por posición del indice
vector00=np.array([1,2,4,6])
vector00=np.insert(vector00, [2,3],[3,5], axis=0)
#observaer que [2,3] son las posiciones elegidas y [3,5] los valores a asignar
vector00

array([1, 2, 3, 4, 5, 6])

In [ ]:
#borrar elementos por posición del indice
vector00=np.delete(vector00, [2,4])
#observaer que [2,4] son las posiciones elegidas para borrar
vector00

array([1, 2, 4, 6])

####**Operaciones con vectores**

#####**Entre un vector y un escalar**

In [ ]:
#creación array
vector=np.array([1,2,3,4])
#creación vector fila
vertor_1=np.array([[1,2,3,4]])
#creación vector columna
vertor_2=np.array([[1],[2],[3],[4]])


In [ ]:
#suma
vector+2

array([3, 4, 5, 6])

In [ ]:
#suma
vector_1+2

array([[3, 4, 5, 6]])

In [ ]:
#suma
vector_2+2

array([[3],
       [4],
       [5],
       [6]])

In [ ]:
#resta
vector-1

array([0, 1, 2, 3])

In [ ]:
#resta
vector_1-1

array([[0, 1, 2, 3]])

In [ ]:
#resta
vector_2-1

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
#multiplicación
vector*2

array([2, 4, 6, 8])

In [ ]:
#multiplicación
vector_1*2

array([[2, 4, 6, 8]])

In [ ]:
#multiplicación
vector_2*2

array([[2],
       [4],
       [6],
       [8]])

In [ ]:
#división
vector/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
#división
vector_1/2

array([[0.5, 1. , 1.5, 2. ]])

In [ ]:
#división
vector_2/2

array([[0.5],
       [1. ],
       [1.5],
       [2. ]])

In [ ]:
#potencia
vector**2

array([ 1,  4,  9, 16])

In [ ]:
#potencia
vector_1**2

array([[ 1,  4,  9, 16]])

In [ ]:
#potencia
vector_2**2

array([[ 1],
       [ 4],
       [ 9],
       [16]])

#####**Entre un vector y un vector**

In [ ]:
vector=np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [ ]:
vector1=np.array([5,6,7])
vector1

array([5, 6, 7])

In [ ]:
vector+vector1
#devuelve error porque ambos arrays deben tener la misma dimensión interna

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

Solo es posible operar entre vectores de igual dimensión

In [ ]:
vector2=np.array([5,6,7,8])
vector2

array([5, 6, 7, 8])

In [ ]:
#suma
vector + vector2

array([ 6,  8, 10, 12])

In [ ]:
#suma entre vector fila y columna
vector_1=np.array([[1,2,3]])
vector_2=np.array([[1],[2],[3]])
vector_1 + vector_2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
#resta
vector2 - vector

array([4, 4, 4, 4])

In [ ]:
#resta entre vector fila y columna
vector_1=np.array([[1,2,3]])
vector_2=np.array([[1],[2],[3]])
vector_2 - vector_1

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [ ]:
#multipl1cación
vector*vector2

array([ 5, 12, 21, 32])

In [ ]:
#multiplicación entre vector fila y columna
vector_1=np.array([[1,2,3]])
vector_2=np.array([[1],[2],[3]])
vector_2 * vector_1

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
#división
vector2/vector

array([5.        , 3.        , 2.33333333, 2.        ])

In [ ]:
#división entre vector fila y columna
vector_1=np.array([[1,2,3]])
vector_2=np.array([[1],[2],[3]])
vector_2 / vector_1

array([[1.        , 0.5       , 0.33333333],
       [2.        , 1.        , 0.66666667],
       [3.        , 1.5       , 1.        ]])

In [ ]:
#multiplicación escalar entre arrays
vector=np.array([1,2,3,4])
vector2=np.array([5,6,7,8])
np.dot(vector,vector2)

np.int64(70)

In [ ]:
#multiplicación escalar entre vectores
vector_1=np.array([[1,2,3]])
vector_2=np.array([[1],[2],[3]])
np.dot(vector_1,vector_2)

array([[14]])

#####**Filtrado de elementos**

In [ ]:
#obtener solo los elementos múltiplo de dos
vector[(vector % 2 == 0)]

array([2, 4])

In [ ]:
#obtener solo los elementos distintos de dos
vector[vector!=2]

array([1, 3, 4])

In [ ]:
#obtener solo los elementos exactamente igual a dos
vector[vector==2]

array([2])

In [ ]:
#obtener solo los elementos mayores que dos
vector[vector>2]

array([3, 4])

In [ ]:
#obtener solo los elementos mayores o iguales que dos
vector[vector>=2]

array([2, 3, 4])

In [ ]:
#obtener solo los elementos menores que dos
vector[vector<2]

array([1])

In [ ]:
#obtener solo los elementos menores o iguales que dos
vector[vector<=2]

array([1, 2])

####**Ejemplos Sección 2.3.4**

**Ejemplo 2.3.4.1**

Cree un programa donde el usuario ingrese los valores entre 5 y 50, cada 10, se cree un array y que devuelva true o false al verificar si todos los valores son múltiplo de 5.

In [ ]:
vector=np.arange(int(input('ingrese el valor inicial: ')),int(input('ingrese el valor final: ')),int(input('ingrese el valor de salto: ')))
verif=vector[(vector % 5 == 0)]>0
print('Los elementos del vector que es de '+str(vector.ndim)+'D son múltiplo de 5: '+str(verif.all()))

ingrese el valor inicial: 5
ingrese el valor final: 50
ingrese el valor de salto: 10
Los elementos del vector que es de 1D son múltiplo de 5: True


**Ejemplo 2.3.4.2**

Cree un programa donde a partir de la cantidad producida [500, 300, 200] celulares, tablets y computadoras respectivamente; los insumos requeridos para la producción de cada producto por unidad (chip, pantalla, horas de trabajo respectivamente):
calulares: [1,1,2]
tablets: [1,1,3]
camputadoras:[2,1,5]
y los costos monetarios de producción [45,30,15]
devuelva el costo total de producción involucrado


In [ ]:
# Se definen los vectores
P = np.array([500, 300, 200])
V_celular = np.array([1, 1, 2])
V_tablet   = np.array([1, 1, 3])
V_computadora   = np.array([2, 1, 5])
Costo_prod = np.array([45, 30, 15])

# Se calcula el total de recursos necesarios
total_recursos = (P[0] * V_celular) + (P[1] * V_tablet) + (P[2] * V_computadora)

# Se calcula el costo total de producción
costo_total = np.dot(total_recursos, Costo_prod)

print('El costo total de producción es $'+str(costo_total))

El costo total de producción es $127500


###**Sección 2.3.5 Matrix**

####**Creación de una Matrix**

In [ ]:
import numpy as np

In [ ]:
#Matriz de 3 x 2

matrix = np.array([[1, 2],[3, 4],[5, 6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Matriz 3 x 2 a partir de arrays
arr1=np.array([1,2])
arr2=np.array([3,4])
arr3=np.array([5,6])
matrix1=np.array([arr1,arr2,arr3])
matrix1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Matriz 3 x 2 a partir de listas
list1=[1,2]
list2=[3,4]
list3=[5,6]
matrix2=np.array([list1,list2,list3])
matrix2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Matriz 3 x 2 a partir de tuplas
tup1=(1,2)
tup2=(3,4)
tup3=(5,6)
matrix3=np.array([tup1,tup2,tup3])
matrix3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#matriz de 3 x 2 a partir de un solo array
arr = np.array([1, 2, 3, 4, 5, 6])
matrix4 = arr.reshape(3, 2)
matrix4

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#convertir matriz de 3 x 2 a un solo array
vector=matrix.reshape(-1)
vector

array([1, 2, 3, 4, 5, 6])

####**Acceso a los elementos**

In [ ]:
#obtener primer elemento
matrix[0,0]

np.int64(1)

In [ ]:
#obtener los dos primeros elementos de la primera fila
matrix[0,0:2]

array([1, 2])

In [ ]:
#obtener los dos primeros elementos de la primera columna
matrix[0:2,0]

array([1, 3])

In [ ]:
#obtener los últimos dos elementos por fila
matrix[2,0:2]

array([5, 6])

In [ ]:
#obtener los últimos dos elementos por columna
matrix[1:3,1]

array([4, 6])

####**Modificación de elementos**

In [ ]:
#se modifica el último elemento
matrix[2,1]=10
matrix

array([[ 1,  2],
       [ 3,  4],
       [ 5, 10]])

In [ ]:
#se modifica la última fila
matrix[2,:]=[5,6]
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#se modifica la última columna
matrix[0:3,1:2]=[[10],[11],[12]]
matrix

array([[ 1, 10],
       [ 3, 11],
       [ 5, 12]])

In [ ]:
#se regresa a lo valores originales
matrix[0:3,1:2]=[[2],[4],[6]]
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#agregar una columna
matrix0 =np.hstack((matrix, [[10],[11],[12]]))
matrix0

array([[ 1,  2, 10],
       [ 3,  4, 11],
       [ 5,  6, 12]])

In [ ]:
#agregar una columna
matrix00 =np.vstack((matrix,[[10,11]]))
matrix00

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 11]])

####**Funciones más frecuentes**

#####**Las que no modifican el objeto**

In [ ]:
#cantidad de elementos
len(matrix)

3

In [ ]:
#cantidad de elementos dentro de los elementos
matrix.size

6

In [ ]:
#dimensión de la matriz
matrix.ndim

2

In [ ]:
#dimensiones
matrix.shape

#3 filas, 2 columnas

(3, 2)

In [ ]:
#agregar una fila

matrix1=np.concatenate((matrix,[np.array([1,1])]), axis=0)
matrix1

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1]])

In [ ]:
#borrar una fila
matrix1=np.delete(matrix1,3, axis=0)
matrix1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# elemento máximo
np.max(matrix)

np.int64(6)

In [ ]:
# elemento mínimo
np.min(matrix)

np.int64(1)

In [ ]:
#sumar los elementos
np.sum(matrix)

np.int64(21)

#####**Funciones particulares de cálculos**

In [ ]:
#trasponer una matriz

matrix.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
#determinante
matrix_cuadrada=np.array([[1,2],[3,4]])
np.linalg.det(matrix_cuadrada)

np.float64(-2.0000000000000004)

In [ ]:
#diagonal
matrix.diagonal()

array([1, 4])

In [ ]:
#traza
matrix.trace()

np.int64(5)

In [ ]:
#invertir una matriz
np.linalg.inv(matrix_cuadrada)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#adjunta de una matriz
np.linalg.inv(matrix_cuadrada).T

array([[-2. ,  1.5],
       [ 1. , -0.5]])

In [ ]:
MATRIX=np.array([[3,2],[1,0]])
np.linalg.inv(MATRIX).T

array([[ 0. ,  0.5],
       [ 1. , -1.5]])

In [ ]:
#valores propios y vectores propios

eigenvalues= np.linalg.eig(matrix_cuadrada)[0]
eigenvalues

array([-0.37228132,  5.37228132])

In [ ]:
# vectores propios

eigenvectors= np.linalg.eig(matrix_cuadrada)[1]
eigenvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

####**Operaciones con matrices**

#####**Operaciones con un escalar**

In [ ]:
#suma de un escalar
matrix_cuadrada +3

array([[4, 5],
       [6, 7]])

In [ ]:
#resta de un escalar
matrix_cuadrada -1

array([[0, 1],
       [2, 3]])

In [ ]:
#multiplicación por un escalar
matrix_cuadrada *3

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
#división por un escalar
matrix_cuadrada /2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [ ]:
#potencia
matrix_cuadrada**2

array([[ 1,  4],
       [ 9, 16]])

#####**Operaciones entre matrices**

In [ ]:
#suma
matrix_cuadrada_2=np.array([[5,6],[7,8]])
matrix_cuadrada + matrix_cuadrada_2

array([[ 6,  8],
       [10, 12]])

In [ ]:
#resta

matrix_cuadrada - matrix_cuadrada_2

array([[-4, -4],
       [-4, -4]])

In [ ]:
#multiplicación

matrix_cuadrada*matrix_cuadrada_2

#notar que lo hace fila a fila

array([[ 5, 12],
       [21, 32]])

In [ ]:
#multiplicación escalar

np.dot(matrix_cuadrada,matrix_cuadrada_2)

array([[19, 22],
       [43, 50]])

In [ ]:
#división

matrix_cuadrada_2/matrix_cuadrada

#notar que lo hace fila a fila

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

####**Filtrado de elementos**

In [ ]:
#obtener elementos multiplo de dos
matrix_cuadrada[(matrix_cuadrada % 2 == 0)]

array([2, 4])

In [ ]:
#obtener elementos distintos de 2
matrix_cuadrada[matrix_cuadrada!=2]

array([1, 3, 4])

In [ ]:
matrix_cuadrada <1

array([[False, False],
       [False, False]])

In [ ]:
matrix_cuadrada>0

array([[ True,  True],
       [ True,  True]])

In [ ]:
matrix_cuadrada <5

array([[ True,  True],
       [ True,  True]])

In [ ]:
matrix_cuadrada <=2

array([[ True,  True],
       [False, False]])

In [ ]:
matrix_cuadrada >=2

array([[False,  True],
       [ True,  True]])

####**Ejemplos Sección 2.3.5**

**Ejemplo 2.3.4.1**

Construya una matriz con los siguientes vectores fila: (1,2,3,4), (5,6,7,8), (9,10,11,None), (13,None,15,None)

Realice las siguientes operaciones en celdas individuales:

a) Verifique las dimensiones

b) Obtenga el elemento que se encuentra en la fila 2 y columna 3

c) Reemplace el primer valor None por 12, el segundo None por 14 y el tercero por 16.

d) Verifique si los elementos son negativos

e) Ahora calcule la suma de las columnas y asigne el resultado a un vector denominado vector1

In [ ]:
  #se crea la matriz con los vectores dados ingresandolos como filas
  matrix=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,None],
            [13,None,15,None]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, None],
       [13, None, 15, None]], dtype=object)

In [ ]:
#a) se verifican dimensiones
matrix.shape

(4, 4)

In [ ]:
#b) se obtiene el elelemento de la fila 2 y columna 3

#recordar que el indice comienza en 0. Entonces fila 2 -> posición 1 y columna 3 -> posición 2

matrix[1,2]

7

In [ ]:
#c) se reemplazan los valores None por 12, 14 y 16

matrix[2,3]=12
matrix[3,1]=14
matrix[3,3]=16

matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=object)

In [ ]:
#d) se verifica si los elementos son negativos

matrix<0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#e) se calcula la suma de las columnas y se asigna el resultado a un vector denominado vector1

vector1=np.sum(matrix, axis=0)
vector1

array([28, 32, 36, 40], dtype=object)

**Ejemplo 2.3.4.2**

Un inversor posee \$12.000 para invertir en tres fondos diferentes. Los fondos presentan los siguientes rendimientos: fondo de renta fija paga un 3 % de interés anual; fondo de renta variable paga un 4 % anual; fondo de criptoactivos que pagan un 7 % anual. Sabiendo que invertirá \$4.000 más en criptoactivos que en fondos variables y que el interés total a obtener en un año es $670. ¿Qué monto invertirá en cada tipo de fondo?

In [ ]:
A=np.array([[1,1,1],
            [0,-1,1],
            [0.03,0.04,0.07]])

invA=np.linalg.inv(A)
d=np.array([12000,4000,670])
x=np.dot(invA,d)
print('La distribución de los montos a invertir son: $'+str(round(x[0]))+' en fondos de renta fija, $'+str(round(x[1]))+' en fondos de renta variable, $'+str(round(x[2]))+' en fondos de criptoactivos')

La distribución de los montos a invertir son: $2000 en fondos de renta fija, $3000 en fondos de renta variable, $7000 en fondos de criptoactivos
